export const RSA_CONSTANTS = {
  ALGORITHM: 'RSA-OAEP',

  KEY_IMPORT_FORMAT: 'spki',
  KEY_WRAP_FORMAT: 'raw', // ArrayBuffer
  KEY_FORMAT: 'base64',
  PLAIN_TEXT_FORMAT: 'base64',
  CIPHER_TEXT_FORMAT: 'base64',

  KEY_OPTIONS: {
    modulusLength: 2048,
    hash: 'SHA-256'
  },

  KEY_USAGE: ['wrapKey']
}

const AES_256_GCM_KEY_LENGTH = 32
const AES_256_GCM_KEY_BIT_LENGTH = AES_256_GCM_KEY_LENGTH * 8
const AES_256_GCM_KEY_STRING_LENGTH = 4 * Math.ceil(AES_256_GCM_KEY_LENGTH / 3)

export const AES_256_GCM_CONSTANTS = {
  ALGORITHM: 'AES-GCM',
  KEY_USAGE: ['encrypt', 'decrypt'],
  KEY_LENGTH: AES_256_GCM_KEY_LENGTH,
  KEY_BIT_LENGTH: AES_256_GCM_KEY_BIT_LENGTH,
  KEY_STRING_LENGTH: AES_256_GCM_KEY_STRING_LENGTH,
  IV_FORMAT: 'base64',
  IV_LENGTH: 16,
  PLAIN_TEXT_FORMAT: 'utf8',
  CIPHER_TEXT_FORMAT: 'base64',
  AUTH_TAG_LENGTH: 16,
  DATA_SEPARATOR: '.'
}
